[build]

  base = "/"
  publish = "src/"
  functions = "functions/"

[context.production]

  branchname = "live"

[context.deploy-preview.environment]

  FIREBASE_PROJECT_COLLECTION = "images-test"

[context.branch-deploy.environment]

  FIREBASE_PROJECT_COLLECTION = "images-test"